### PR TITLE
116 - Replace pip by uv

### PR DESCRIPTION
**Pull request by ecourtois**
[uv](https://docs.astral.sh/uv) is "an extremely fast Python package and project manager, written in Rust".

Some of its features are particularly interesting for COGIP tools:

* Very fast packages installation
Allow much faster installation on Raspberry PI.

* Python installation independent from the OS
Easier to select a Python version (3.12 currently) to have the same versions on the development PC
and on the Raspberry Pi, independently from the OS installed on each platform.
The python version is specified in the .python-version file
and version controlled.

* Very good cache management
Allow to deploy COGIP tools on Raspberry Pi without internet connection
if dependencies are already in the cache.
This implies removal of the devpi server previously installed on the Beacon to cache dependencies.

* Ability to install only requirements from a pyproject file
Having separate requirements.txt files is not required anymore, so dependencies are now included
directly in pyproject.toml.

* New feature to declare indexes and pin packages to a specific index
Very useful to force pre-compiled ydlidar package (and only this one) to be installed from our Github repository.
These properties are defined in pyproject.toml so it does not require system-wide configuration.

Dockerfiles have been re-written to take advantage of uv features to improve docker image layers caching
to speed-up build phases.

### CODE REVIEW

**Comment by gdoffe** [comment]
LGTM, nothing special as I am not the expert.

However 2 questions:

> Allow much faster installation on Raspberry PI.

Do you have some ratios ?


> New feature to declare indices and pin packages to a specific index
> Very useful to force pre-compiled ydlidar package (and only this one) to be installed from our Github repository.
> These properties are defined in pyproject.toml so it does not require system-wide configuration.

I understand the purpose and find it cool, however I do not understand the how, any doc/starting point on this ?

**Review by gdoffe — APPROVED** [review]

**Comment by ecourtois** [comment]
> > Allow much faster installation on Raspberry PI.
> 
> Do you have some ratios ?

|               |  pip  |  uv  |
|---------------|------:|-----:|
| Without cache |  5m38 | 2m47 |
| With cache    |   40s |  16s |

> > New feature to declare indexes and pin packages to a specific index
> > Very useful to force pre-compiled ydlidar package (and only this one) to be installed from our Github repository.
> > These properties are defined in pyproject.toml so it does not require system-wide configuration.
> 
> I understand the purpose and find it cool, however I do not understand the how, any doc/starting point on this ?

https://docs.astral.sh/uv/configuration/indexes/

**Review by gdoffe — APPROVED** [review]
LGTM ! Good job !

**Review by Starbeuck — APPROVED** [review]
LGTM!

**Pull request merged**
